---
title: "vizu_interativa"
output: 
    flexdashboard::flex_dashboard:
        storyboard: true
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(plotly)
#library(hrbrthemes)
#theme_set(theme_ipsum())

respostas = read_csv(here::here("data/enade-ufcg-2017.csv"),
                     col_types = "cccdccdddc")

cursos = respostas %>% 
    group_by(UF) %>% 
    summarise(n = n(), 
              media = mean(media))

criterios = respostas %>% 
    group_by(UF, categoria) %>% 
    summarise(media = mean(media))
```

### Parte 1

```{r}
p = respostas %>%
    filter(categoria != "Outros") %>%
    mutate(Categoria = str_glue("{categoria}\nMédia: {media}")) %>% 
    ggplot(aes(
        x = reorder(categoria, media),
        y = reorder(NOME_CURSO, media),
        fill = media, 
        label = Categoria
    )) +
    geom_tile() +
    labs(
    x = "Categoria",
    y = "Curso",
    title = "Cursos e suas respectivas médias nas categorias avaliadas",
    subtitle = "Quadrados indicam a média do curso para cada categoria"
) +
    scale_fill_viridis() + 
    theme(legend.position = "bottom")

p
ggplotly(p, tooltip = "label")
```

***

### Parte 2

```{r}
p = respostas %>% 
    mutate(Formandos = str_glue("{n}")) %>% 
    ggplot(aes(x = n, y = reorder(NOME_CURSO, n), label = Formandos)) + 
    geom_point() +
    scale_x_log10()
    p
ggplotly(p, tooltip = "label")
```


